# Generated by Django 3.1.2 on 2020-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='age_group',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='type_of_case',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
