# Generated by Django 3.1.2 on 2020-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20201024_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='age_group',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_case',
            field=models.CharField(default='', max_length=20),
        ),
    ]
