# Generated by Django 3.1.2 on 2021-04-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20210331_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default=True, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
