# Generated by Django 3.1.2 on 2021-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20210416_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
